sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 530153
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: webproject-02
  redis:
    host: localhost
    port: 6379
    auth: 123456
    database: 10
  wechat:
    appid:
    secret:
